"""Add manifest column to plugins

Revision ID: 91c484afabaa
Revises: 0e31d31069f0
Create Date: 2026-09-10 05:05:08.858143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c484afabaa'
down_revision: Union[str, None] = '0e31d31069f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugins', sa.Column('manifest', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugins', 'manifest')
    # ### end Alembic commands ###
